### ISSUE TITLE
[Example] Pets don't teleport with player when being summoned over a short distance

### ISSUE THREAD

**Issue by kelno** [SunstriderEmu/SunBugTracker#1]
**Describe the bug**
When you get summoned by a warlock from a short distance your pet runs to you instead of being summoned with you.

**Character name**
Kelno

**To Reproduce**
1. Have a pet summoned
2. Get summoned by a warlock over a short distance (~50y)

Spell: https://tbcdb.com/?spell=698

**Expected behavior**
Pet should be teleported with the player.

**Additional context**
/

**Comment by ccwower** [comment]
Hello, brother administrator, I am a programming student from the Chinese community. As far as I know, Sunstrider also has members participating in China. I hope I can join and get core code support from you! I will continue to give feedback on bugs submitted by players and players in China

Can you invite me to join the closed source group? Hope to share closed source warehouse
